### ISSUE TITLE
Installing to /usr/bin instead of /usr/local/bin

### ISSUE THREAD

**Issue by fiskenslakt** [emanresudab/cmenu#2]
https://github.com/emanresudab/cmenu/blob/e137e8166ce7f4d0dca12221b6128650a050095e/makefile#L8

> `/usr/bin` is for distribution-managed normal user programs.
`/usr/local/bin` is for normal user programs not managed by the distribution package manager, e.g. locally compiled packages. You should not install them into /usr/bin because future distribution upgrades may modify or delete them without warning.

[Source](https://unix.stackexchange.com/a/8658)

**Comment by emanresudab** [comment]
Ah alright, I'll update the install path
